language: python
sudo: required
dist: xenial
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements-dev.txt
script:
- pytest
- pylint ./confj
deploy:
  provider: pypi
  user: aleosd
  password:
    secure: Uf6b29i8DSH+4FEHVvdHPDPvzNx32QLmkjbKPC6n4p1jrcDIgte2ZHbgxBkeZ2P+Cfycrfv+NUKc0ciz+FdMPBLEudVzyhpTPivB9glsvhyr8jfVOWEfknG51mcmQAm3qus4R6FQwaC3B2xj7wmhEBaqUfP7SSwNXZg2O00e9WvrEkB5cvsQI7h8fJJ5oh9IRk3desZGuxwsA5bJ4DgwhWHsv/qjbYF861dDSBWVkK5LeduGmn0Jwj5FfZo8JOkVRni19xCKsCOiZH5eCZB7QqixcmE+3cBLoUlfn+w8oAjteHQtK0dP8bhKqyn4o68nDx7TDswAI09lTy5Clh4zLtbUzwh509uclpx3hTPi2JuR6aPtoAs2zE3Iu0CcMobX0n5ysl/3WGjxMCTig60oNlRCA8MauEue0jmkPgT7TxaBhoul7dai4gQtMyC8cTFfQinVDSpQpjxGauOFXDZEO6ED7Y2vgz2BrcZJCgX5y0PaWw52I/theHTrlohQsHuzAZ/XHKGvrqkD2xHBBr+djsb4LH/ufV/gShJCWjf9N2WPIRXMUUs9SLkUJ/PeMOSzZtsI5cfXvI/+r80btE6WzfGw2YOhq7PhA6T4mQp/cMBHOySvSldf2qcCq6Y1eyz+psW/g1SNZ3xvwknkWJfxNt76khSkgsCuI6uHtNrcAL0=
  on:
    tags: true
    python: '3.7'
